### ISSUE TITLE
Input number prop bug

### ISSUE THREAD

**Issue by joeyberkovitz** [oruga-ui/oruga#1147]
### Overview of the problem

**Oruga** version: 0.9.2

### Description

The `o-input` number prop is described as a flag in the docs, similar to `rounded` where no value has to be passed and the presence of the prop indicates that the input model should be converted to a number. In Oruga 0.9.2, the prop only works if the value is set to `:number="true"` or `number="true"`. Otherwise a string is returned through the `v-model`

**Comment by mlmoravek** [comment]
Hey, thanks for finding this bug!

For the description:
Normally, when declaring a boolean typed prop, vue will transform the empty passed property from `""` to a `true`, so you can only use `rounded` instead of `rounded="true"`. 
The number property isn't declared as a normal boolean, it's a generic `extends boolean' property. Somehow Vue can't convert the prop from `""` to a `true` for such a prop. So we have to explicitly check whether it is `undefined` or `""`, which means the same as `true`. This check is missed in some places, which makes the `""` check to be `false`.
