### ISSUE TITLE
Add Dialog Component

### ISSUE THREAD

**Issue by mouadTaoussi** [oruga-ui/oruga#225]
### Description
Adding Dialog Component .

### Why Oruga need this feature
Easiest way to propmt or alert the user

**Note:I Might take time becuase I have a Display issue in my Laptop that needs to be fixed first, then work on the feature!**

**Comment by Thaurin** [comment]
Yes, I need this before I can finish migrating to Oruga!

**Comment by Thaurin** [comment]
This is literally keeping me from migrating a Vue 2 web application that is in production to Vue 3 with Oruga with Bulma plugin, then Vue 3!

**Comment by jtommy** [comment]
I got it, in the next release will be available the carousel.
There is a PR but incomplete and I need time to add Oruga features

**Comment by urkle** [comment]
@jtommy @mouadTaoussi so I took a look some at the PR #254 and it currently doesn't really work.  
I have a local branch where I have done some rework on it and have it doing the basic alert dialog now (including working with theme-bulma, but only Vue2 right now)

@jtommy A few questions I have though on how you envision this component working in Oruga.

1) the dialog currently uses them-bulma-specific inner contents (modal-card-head, modal-card, etc..).
   Q: how do you envision exposing this to configuration to allow the best customization by the CSS framework layer?
2) the dialog currently "extends" off of Modal and re-implements a lot of properties and code.
   Q: right now my version just has an o-modal in the body that I am using.  Is that acceptable? or would you still rather have it extend OModal?
What is the "official" set of properties it should expose to the $dialog.* methods?

**Comment by jtommy** [comment]
1. As i told you in this PR there is nothing about Oruga idea. For example there isn't bodyClass prop or no modal class are applied to it. Does it make sense?

About template I don't know.. dialog might be different by modal but usually is only a built-in modal with a template for alert, confirm and prompt.

**Comment by urkle** [comment]
I understand that PR was about a quick and dirty port..  I'm trying to make a PR that is more close to the final "oruga style" idea.  Hence all the questions..  I'd rather build up something useful that can easily be included in the next release vs something that'd have to be redone again to fit more with the Oruga style.

As for why add a dialog component?  Because there is some nicety in having a built-in alert, confirm, and prompt style dialogs in the system.  AND especially if those work in a promise/async+await style manner to make coding easy.  

Or find a way to "easily" provide that kind of thing using the programatic modal? and include some nice examples on how to utilize that? (e.g. like the "tost" examples for notifications)


In the end I am wanting something like this.

```javascript
const result = await this.$oruga.dialog.confirm({
   message: 'Really delete this record?',
   type: 'variant',
});

// Or whatever is decided the return value to be
if (result === true) {
   // do stuff to trigger the deletion.
}
```

VS doing lots of callbacks.

In another project (vue 2-based) where I spent this week switching it from "basic html" to Oruga I found the lack of this construct in Oruga (hence why I am looking at this issue so I can help contribute).  And had to stick with using another library ([vue-modal-dialogs](https://github.com/hjkcai/vue-modal-dialogs)) All for a simple confirm dialog.

**Comment by jtommy** [comment]
I understand that promise way is great and helpful for prompt and confirm.
In other hand dialog UI is only a modal and the good examples could be enough at the moment

**Comment by urkle** [comment]
@jtommy What about a "dialog" promise interface with no component but injects props into a user-provided component to represent their UI and provides a clean way to send back the "response"?  This could (maybe) even be an adjustment of the programatic Modal interface?

**Comment by jtommy** [comment]
Can you make an example to understand better?

**Comment by urkle** [comment]
@jtommy I created PR #314 that has a proposal for handling a "promise/async" modal.open method.

I've tested this in both Vue2 and Vue3 and it works great.

I did change the return contract for modal.open, but it was already inconsistent before.. (Vue2 returned the component instance, Vue3 returned void)

We *could* extend this promise concept to the notifications.open and loading.open as well.

**Comment by jtommy** [comment]
I want to fix Vue 3, because it has to return the component instance instead of void as https://github.com/oruga-ui/oruga/issues/313

**Comment by jtommy** [comment]
@urkle https://github.com/oruga-ui/oruga/blob/dff0a04fde4d2477bc18510d5fbcfd8c880d3850/packages/oruga-next/src/components/modal/index.ts#L35
I think we haven't to return the result of render but only vnode variable.

**Comment by urkle** [comment]
@jtommy to return the component it is actually vnode.component.proxy (that is the same as "this" inside any component method).

I have a PR going up shortly.

**Comment by urkle** [comment]
@jtommy PR #315
