### ISSUE TITLE
o-input issues with ref/focus

### ISSUE THREAD

**Issue by reskes** [oruga-ui/oruga#339]
### Overview of the problem

@oruga-ui/oruga-next: 0.5.5
@oruga-ui/theme-bulma: 0.2.5
vue: 3.2.31

@vueuse/core: 8.2.5

### Description

I'm trying to use the vueuse library's _useFocus_ in combination with Oruga's input element. Not sure if we should call this a bug or a feature request.

This is my code, simplified:

```
.....
  <o-input v-model="model" type="text" ref="focusInput"/>
</template>

<script lang="ts" setup>
.....
const focusInput = ref();

const { focused } = useFocus(focusInput, { initialValue: true });
.....
```

But instead of focusing the native input as expected, nothing happens and the _focused_-value doesn't change.

After checking the affected source-code of oruga and vueuse, I created this quite dirty workaround.
It of course only works for the native type _text_ and only as long there is no change to the Oruga input source-code internally.

```
const focusInput = ref();

// "workaround"
const focusInputComp = computed(() => focusInput.value?.$refs.input);

const { focused } = useFocus(focusInputComp, { initialValue: true });
```

### Expected behavior

Rather pass _ref_ to the native input's _ref_ or maybe at least provide a focus-function/method on the component, to redirect it to the native element's one.

**Comment by mlmoravek** [comment]
Since Oruga 0.8.x:
Since `useFocus` needs a DOM element and the Oruga components are Vue components, the composable is by definition incompatible with Oruga. The template ref contains a vue component not a HTMLElement. You can access the template component with `$el` on the vue component ref. You can also pass an `id` prop to the component and get the input DOM element with native javascript functions and use it for `useFocus`. 

I consider this issue as closed. Feel free to open a new one with specific feature requests or bug reports :)
