### ISSUE TITLE
[Bug] o-autocomplete with append-to-body on a modal

### ISSUE THREAD

**Issue by asadhshujau** [oruga-ui/oruga#373]
### Overview of the problem

**Oruga** version: [0.5.5]
**Vuejs** version: [3.2.37]
**OS/Browser**: Chrome

### Description

happens when **o-autocomplete**  is used with **appendToBody** prop in a programmatic modal with **destroyOnHide** set to **true** and modal is closed

### Steps to reproduce

1. make a component with a o-autocomplete with append-to-body prop on it
3. open a programmatic modal with the component set as the created component and destroyOnHide set to true
4. close the dialog to see the error

### Expected behavior

Close the modal without throwing any errors 

### Actual behavior

Uncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

**Comment by asadhshujau** [comment]
same case for o-inputitems

**Comment by BuffMcBigHuge** [comment]
`o-dropdown` also has this issue. Can reproduce [here](https://codesandbox.io/s/oruga-vue3-notification-test-0hcqxy?file=/src/Modal.vue).

**Comment by asadhshujau** [comment]
o-datepicker too 

probably all the components with a dropdown view has this issue. [not confirmed]

**Comment by jtommy** [comment]
Yes, there 3-4 components that depends on dropdown

**Comment by urkle** [comment]
This issue also occurs with the o-tooltip component.

**Comment by mlmoravek** [comment]
@asadhshujau 
The autocomplete component now (v0.8.x) uses the dropdown component internally. Both the dropdown and modal components now implement the old `append-to-body` feature with the Vue native `teleport` component. 

Is this still a problem?

**Comment by urkle** [comment]
@mmorainville I just (finally) tested an upgrade to oruga 0.8 and the issue is worse.

I don't seem to be getting this specific error anymore, however the popup doesn't show correctly at all (my testing was with the datepicker component).

Date picker in a model
1) with teleport the datepicker component is simply not visible at all
2) turning off teleport the datepicker opens but is severely obscured by the model dialog

Date picker on a page (outside of model)
1) without teleport it works fine
2) with teleport the CSS renders completely wrong (end up with a unstyled mess of text for the date table). (using theme-bulma)

So as of right now I have to revert back to oruga 0.7 until issues are resolved

**Comment by mlmoravek** [comment]
If anyone is still having problems with this, please feel free to open a new issue with updated information.
