### ISSUE TITLE
o-tabs renders its content twice

### ISSUE THREAD

**Issue by IlyaSemenov** [oruga-ui/oruga#532]
### Overview of the problem

**Oruga** version: 0.6.0
**Vuejs** version: 3.3.4
**OS/Browser**: Chrome 112

### Description

`<o-tabs>` renders its content twice.

### Steps to reproduce

```vue
<script lang="ts" setup>
function log(m: string) {
  console.log(m);
}
</script>

<template>
  {{ log('page') }}
  <o-tabs>
    {{ log('o-tabs') }}
    <o-tab-item />
  </o-tabs>
</template>
```

Full reproduction: https://stackblitz.com/edit/nuxt-starter-dvt3na?file=app.vue

1. Click "Open in new tab".
2. Open devtools console
3. Reload page

### Expected behavior

console output:
```
page
o-tabs
```

### Actual behavior

console output:
```
page
o-tabs
o-tabs
```

**Comment by mlmoravek** [comment]
This is a behaviour that comes because of our component architecture and how we have the item components implemented and registered by the parent component. On the initial render, the parent has no child component to render because the childs need to register itself by the parent. When the childs have finished registering, Vue renders the parent template again. This is why the default slot was rendered twice. This behaviour can be seen in some other components such as tabs. 

I do not see this as a real problem, so I am closing this issue. If you have any problems with this, let me know.
