### ISSUE TITLE
o-tab-item content hidden on page load

### ISSUE THREAD

**Issue by gmcinalli** [oruga-ui/oruga#534]
### Overview of the problem

**Oruga** version: 0.6.0
**Nuxt** version: 3.5.1
**OS/Browser**: macOS 13.3.1 (a) / Google Chrome 113.0.5672.126

### Description

The content of `o-tab-item` is hidden on page load if the tab is programmatically selected via v-model on `o-tabs`.

I noticed that this problem doesn't occur if the pre-selected tab is the first available one.

The problem starts to appear from Oruga version `0.5.0`.

### Steps to reproduce

Full reproduction: https://stackblitz.com/edit/nuxt-starter-gqrjtc?file=app.vue

### Expected behavior

The content of the selected tab should be displayed on page load as it was with the pre-0.5.0 versions.

### Actual behavior

The content of the selected tab is hidden on page load until you select another tab and return to the desired one.

**Comment by learntheropes** [comment]
The problem occurs also if the pre-selected tab is the first available one. See my reproduction.

### Overview of the problem

**Oruga** version: oruga-next@0.6.0 (latest)
**Vuejs** version: vue@3.3.4
**Nuxtjs** version: nuxt@3.7.1 (latest)
**OS/Browser**: 
Chromium Version 116.0.5845.179 (Official Build) snap (64-bit) on Ubuntu 22.04.3 LTS
Brave [Version 1.57.53 Chromium: 116.0.5845.114 (Official Build) (64-bit)] on Ubuntu 22.04.3 LTS
Firefox 117.0 (64-bit) on Ubuntu 22.04.3 LTS
Brave 1.56 on IOS 16.6.1
Chrome 116.0.5845.172 on Android 8.0.0


### Description

The data defined inside `script setup` tag, are not available inside Oruga components until there is an interaction of the user with the page.  
I notice this with tabs and input, but probably the same happens also with other components. 

Check a minimal reproduction here: https://stackblitz.com/edit/github-zcrtvq-w7tjtp

### Steps to reproduce

1. Setup Oruga in a Nuxt 3 app
2. On a page or component, set some data in the `script setup` tag
2. Use the data inside an Oruga components. I personally reproduced inside `o-tabs` and `o-input` but probably the same happens also with other components.
3. Run `npm run dev` and open the page in the browser.
4. Notice that the data are not loaded until there is an interaction with the component. On tabs, you can switch to another one and come back. On input, you can focus and unfocus the input.

### Expected behavior

The data should be visible as soon as the page is loaded.

### Actual behavior

The data need the user interaction with the page to be visible.

**Comment by learntheropes** [comment]
A dirty workaround while this get fixed: https://stackblitz.com/edit/github-zcrtvq-fie9nh

**Comment by zhaolinlau** [comment]
when will this bug get fixed?

**Comment by mlmoravek** [comment]
@zhaolinlau I will look at it when I have some time.

**Comment by mlmoravek** [comment]
@gmcinalli Could you check again with version 0.8.x?

**Comment by gmcinalli** [comment]
Hi @mlmoravek, unfortunately I'm on Vue 2, so the last version that I can try is 0.7.0.

**Comment by jtommy** [comment]
@zhaolinlau @learntheropes any news?

**Comment by mlmoravek** [comment]
@messenjer Thanks for checking this. 

If anyone has any further problems with this, please let me know or reopen this issue again :)
