### ISSUE TITLE
Dropdown with triggers on mobile res doesnt show modal correctly

### ISSUE THREAD

**Issue by Diogo-Coding** [oruga-ui/oruga#609]
### Overview of the problem

**Oruga** version: [0.7.0]
**Oruga Bulma** version: [0.2.11]
**Vuejs** version: [3.2.13]
**OS/Browser**: Chrome

### Description

Adding `":triggers="['hover', 'focus', 'click']"` to the dropdown component options makes it show incorrectly for mobile screens the modal with the options

if you remove the triggers prop it will show correctly

### Steps to reproduce

1. Add/Remove `:triggers="['hover', 'focus','click']"`

**Comment by mlmoravek** [comment]
I think this is because the mobileClass is not applied if it is `hoverable`.

```
{
    [this.computedClass("mobileClass", "o-drop--mobile")]:  
       this.isMobileModal &&  
       this.isMatchMedia &&  
       !this.hoverable,  
},
```
[soruce link](https://github.com/oruga-ui/oruga/blob/33f2cd53d7fdba1b36a9173a0fbefe9daf8f7aa9/packages/oruga-next/src/components/dropdown/Dropdown.vue#L223C1-L228C19)
                
                
To me, a better solution would be to drop the 'hover' trigger if the client is a mobile agent (not just a small screen) and react the same as the 'click' trigger on a mobile agent. 

@jtommy What do you think?
