### ISSUE TITLE
Autocomplete: make vmodel be the selected option

### ISSUE THREAD

**Issue by mlmoravek** [oruga-ui/oruga#872]
### Description

The vmodel of the autocomplete component is not the selected option. The vmodel is the input value, which can be an option or a property, defined by the field prop, of an option. So the vmodel is a string because the input value is a string (I think the o-input does not work for number, even a number type is acceptable, but that is a topic for later).

Currently the selected option is only emitted by the select event, and doesn't have a two-way binding.
We should change that, to be the vmodel be the selected option.
This will be a breaking change.

**Comment by whiplashwebb** [comment]
@mlmoravek this would be really handy, I've been thinking about something similar so I can control the selected item easier. However, i think we need two-way bindings on the query _and_ the selected option, rather than replacing one with the other. This would make this a non-breaking enhancement which i think is a big plus. Please don't make me refactor all of my autocompletes lol.
