### ISSUE TITLE
Add way to skip all or part of components registration

### ISSUE THREAD

**Issue by l00k** [oruga-ui/oruga#891]
### Description
In my project I'm wrapping some components of oruga (to add project specific functionality).
Still I want to use it as `<o-name>` component - so when I register it in vue I get warnings like:
```
Component "OButton" has already been registered in target app.
``` 

That is why I would like to have options to skip some components registration.
PR prepared.

### Why Oruga need this feature
Above I've present my particular case, but I can imagine this feature to be used "widely".
Considering it is really small (what's so more it is optional) change I suppose it could be merged.

**Comment by mlmoravek** [comment]
Hey @l00k, to be clear, if you don't want to register all components, each component also exports its own plugin which you can use to register the component globly, which is documented here: https://oruga-ui.com/documentation/#individual-components-imports-tree-shaking

Here is an example, you can create your own custom vue plugin that registers all the components you want to include: 
```
// MyOrugaPlugin.ts

// import all plugins for only the component you need
import { Button, Sidebar, Menu, Icon, OrugaConfig } from '@oruga-ui/oruga-next';

// import any custom plugin you want
import { bulmaConfig } from '@oruga-ui/theme-bulma';

export default {
  install(app, options) {
    // register the plugins
    app.use(Button);
    app.use(Sidebar);
    app.use(Menu);
    app.use(Icon);

   // register the oruga config plugin with you custom theme config
   app.use(OrugaConfig, bulmaConfig);
  }
}
```


So it is already possible to include only the components you want, rather than excluding unwanted components, which is the way your feature works. So I don't think we need to exclude individual components.

**Comment by l00k** [comment]
Makes sense! Thx
